version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.5-stretch

defaults: &defaults
  executor: python
  environment:
    IMAGE_NAME: neuromation/ml-recipe-midi-generator

orbs:
  docker: circleci/docker@0.5.20


jobs:

  build_and_test:
    <<: *defaults

    steps:
      - setup_remote_docker
      - checkout
      - run: &install_dependencies
          name: Install Dependencies, Configure Environment
          command: |
            pip install --user --upgrade pip neuromation
            pip install --user -r .circleci/requirements.txt
            neuro config login-with-token $NEURO_TOKEN
            neuro config show

      - run:
          name: Build Image
          command: |
            export IMAGE_REF=$IMAGE_NAME:$CIRCLE_BUILD_NUM
            export PROJECT_PATH_STORAGE=storage:build-$CIRCLE_BUILD_NUM
            export CUSTOM_ENV_NAME=image:$IMAGE_REF
            make setup __BAKE_SETUP=yes | tee

            make -f test.mk _generate_random_label > /tmp/test-id.txt
            export TAG="test-id:$(cat /tmp/test-id.txt)"
            make -f test.mk test_jupyter TRAINING_MACHINE_TYPE=cpu-small \
                RUN_EXTRA="--tag=$TAG" | tee
            make -f test.mk test_jupyter TRAINING_MACHINE_TYPE=gpu-small \
                RUN_EXTRA="--tag=$TAG" | tee
            make -f test.mk test_jupyter_baked TRAINING_MACHINE_TYPE=cpu-small \
                RUN_EXTRA="--tag=$TAG" | tee
            make -f test.mk test_jupyter_baked TRAINING_MACHINE_TYPE=gpu-small \
                RUN_EXTRA="--tag=$TAG" | tee

      - run:
          name: Kill jobs left
          command: |
            export JOBS_LEFT=$(neuro -q ps --tag "test-id:`cat /tmp/test-id.txt`")
            [ ! "$JOBS_LEFT" ] || neuro kill $JOBS_LEFT
          when: always

  deploy:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: *install_dependencies

      - run:
          name: Pull Image
          command: |
            export IMAGE_REF=$IMAGE_NAME:$CIRCLE_BUILD_NUM
            neuro pull image:$IMAGE_REF | tee
            echo "CIRCLE_TAG=$CIRCLE_TAG"
            docker tag $IMAGE_REF $IMAGE_NAME:$CIRCLE_TAG
            docker tag $IMAGE_REF $IMAGE_NAME:latest
      - docker/check
      - docker/push:
          image: neuromation/ml-recipe-midi-generator
          tag: $CIRCLE_TAG,latest


workflows:
  version: 2

  main:
    jobs:
      - build_and_test:
          filters:
            tags:
              ignore:
                - /.*/

  deploy:
    jobs:
      - build_and_test:
          filters:
            tags:
              only:
                - /.*/
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /.*/