version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.5-stretch

defaults: &defaults
  executor: python

orbs:
  docker: circleci/docker@0.5.20


jobs:

  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --user -r .circleci/requirements.txt
      - run:
          name: Build Image
          command: |
            make -f test.mk falso
            false

            neuro config login-with-token $NEURO_TOKEN
            neuro config docker
            export IMAGE_NAME=neuromation/ml-recipe-midi-generator
            export IMAGE_REF=$IMAGE_NAME:$CIRCLE_BUILD_NUM
            export IMAGE_URI=image:$IMAGE_REF
            export PROJECT_PATH_STORAGE=storage:build-$CIRCLE_BUILD_NUM
            export CUSTOM_ENV_NAME=$IMAGE_URI
            make setup __BAKE_SETUP=yes

            echo "Testing mounted recipe on cpu..."
            make -f test.mk test_jupyter_demo PROJECT_PATH_ENV=/midi-generator TRAINING_MACHINE_TYPE=cpu-small
            echo "Testing mounted recipe on GPU..."
            make -f test.mk test_jupyter_demo PROJECT_PATH_ENV=/midi-generator TRAINING_MACHINE_TYPE=gpu-small

            echo "Testing baked recipe on cpu..."
            make -f test.mk test_jupyter_demo PROJECT_PATH_ENV=/project-local  TRAINING_MACHINE_TYPE=cpu-small
            echo "Testing baked recipe on GPU..."
            make -f test.mk test_jupyter_demo PROJECT_PATH_ENV=/project-local  TRAINING_MACHINE_TYPE=gpu-small

            neuro pull $IMAGE_URI
            echo "CIRCLE_TAG=$CIRCLE_TAG"
            docker tag $IMAGE_REF $IMAGE_NAME:$CIRCLE_TAG
            docker tag $IMAGE_REF $IMAGE_NAME:latest
      - docker/check
      - docker/push:
          image: neuromation/ml-recipe-midi-generator
          tag: $CIRCLE_TAG,latest


workflows:
  version: 2

  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: CHANGEME
            tags:
              only:
                - /.*/
