version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.5-stretch

defaults: &defaults
  executor: python

orbs:
  docker: circleci/docker@0.5.20


jobs:

  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install --user --upgrade pip neuromation
            pip install --user -r .circleci/requirements.txt
      - run:
          name: Build Image
          command: |
            neuro config login-with-token $NEURO_TOKEN
            neuro config show
            neuro config docker
            export IMAGE_NAME=neuromation/ml-recipe-midi-generator
            export IMAGE_REF=$IMAGE_NAME:$CIRCLE_BUILD_NUM
            export IMAGE_URI=image:$IMAGE_REF
            export PROJECT_PATH_STORAGE=storage:build-$CIRCLE_BUILD_NUM
            export CUSTOM_ENV_NAME=$IMAGE_URI
            make setup __BAKE_SETUP=yes | tee

            export PROJECT_PATH_ENV=/midi-generator
            make -f test.mk test_jupyter_demo TRAINING_MACHINE_TYPE=cpu-small | tee
            echo -e "\n[+] Test passed: $PROJECT_PATH_ENV on CPU\n"
            make -f test.mk test_jupyter_demo TRAINING_MACHINE_TYPE=gpu-small | tee
            echo -e "\n[+] Test passed: $PROJECT_PATH_ENV on GPU\n"

            export PROJECT_PATH_ENV=/project-local
            make -f test.mk test_jupyter_demo TRAINING_MACHINE_TYPE=cpu-small | tee
            echo -e "\n[+] Test passed: $PROJECT_PATH_ENV on CPU\n"
            make -f test.mk test_jupyter_demo TRAINING_MACHINE_TYPE=gpu-small | tee
            echo -e "\n[+] Test passed: $PROJECT_PATH_ENV on GPU\n"

            neuro pull $IMAGE_URI | tee
            echo "CIRCLE_TAG=$CIRCLE_TAG"
            docker tag $IMAGE_REF $IMAGE_NAME:$CIRCLE_TAG
            docker tag $IMAGE_REF $IMAGE_NAME:latest
      - docker/check
      - docker/push:
          image: neuromation/ml-recipe-midi-generator
          tag: $CIRCLE_TAG,latest


workflows:
  version: 2

  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: CHANGEME
            tags:
              only:
                - /.*/
